# Projeto Python IA: Inteligência Artificial e Previsões

### Case: Score de Crédito dos Clientes

Você foi contratado por um banco para conseguir definir o score de crédito dos clientes. Você precisa analisar todos os clientes do banco e, com base nessa análise, criar um modelo que consiga ler as informações do cliente e dizer automaticamente o score de crédito dele: Ruim, Ok, Bom

Arquivos da aula: https://drive.google.com/drive/folders/1FbDqVq4XLvU85VBlVIMJ73p9oOu6u2-J?usp=drive_link

In [15]:
# passo 0 - Entender o desafio da empresa que você vai resolver
# passo 1 - Importar base de dados
# passo 2 - Preparar base de dados para a inteligência artificial
# passo 3 - Criar um modelo de inteligência artificial-> Prever o score Bom, Ruim ou Médio
# passo 4 - Escolher qual o melhor modelo de IA 
# passo 5 - Usar a IA para definir o score de crédito
!pip install pandas numpy scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.26.4)
Requirement already satisfied: scikit-learn in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2024.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.13.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\tecnosys\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [22]:
# Importar Base de Dados
import sklearn
import pandas as pd
tabela = pd.read_csv("clientes.csv")
display(tabela)

C:\Users\TecnoSys\AppData\Local\Temp\ipykernel_5948\2247965832.py:4: DtypeWarning: Columns (0,1,2,4,5,6,7,8,9,10,11,13,14,15,16,18,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  tabela = pd.read_csv("clientes.csv")

,x,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,y
0,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
1,3392,1,23,cientista,19114.12,3,4,3,4,3,...,265,21.46538026,alto_gasto_pagamento_baixos,312.4940887,Good,1,1,1,1,0
2,3392,2,23,cientista,19114.12,3,4,3,4,3,...,266,21.46538026,baixo_gasto_pagamento_alto,284.6291625,Good,1,1,1,1,0
3,3392,3,23,cientista,19114.12,3,4,3,4,3,...,267,21.46538026,baixo_gasto_pagamento_medio,331.2098629,Good,1,1,1,1,0
4,3392,4,23,cientista,19114.12,3,4,3,4,5,...,268,21.46538026,baixo_gasto_pagamento_baixo,223.4513097,Good,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99998,37932,4,25,mecanico,39628.99,4,6,7,2,23,...,378,24.028477,alto_gasto_pagamento_alto,479.866228,Poor,1,0,0,0,1
99999,37932,5,25,mecanico,39628.99,4,6,7,2,18,...,379,24.028477,alto_gasto_pagamento_medio,496.65161,Poor,1,0,0,0,1
100000,37932,6,25,mecanico,39628.99,4,6,7,2,27,...,380,24.028477,alto_gasto_pagamento_alto,516.809083,Poor,1,0,0,0,1
100001,37932,7,25,mecanico,39628.99,4,6,7,2,20,...,381,24.028477,baixo_gasto_pagamento_alto,319.164979,Standard,1,0,0,0,1
100002,37932,8,25,mecanico,39628.99,4,6,7,2,18,...,382,24.028477,alto_gasto_pagamento_medio,393.673696,Poor,1,0,0,0,1

In [21]:
# passo 2 - Preparar base de dados para a inteligência artificial
display(tabela.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100003 entries, 0 to 100002
Data columns (total 25 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   x            100003 non-null  object
 1   Unnamed: 1   100001 non-null  object
 2   Unnamed: 2   100001 non-null  object
 3   Unnamed: 3   100001 non-null  object
 4   Unnamed: 4   100001 non-null  object
 5   Unnamed: 5   100001 non-null  object
 6   Unnamed: 6   100001 non-null  object
 7   Unnamed: 7   100001 non-null  object
 8   Unnamed: 8   100001 non-null  object
 9   Unnamed: 9   100001 non-null  object
 10  Unnamed: 10  100001 non-null  object
 11  Unnamed: 11  100001 non-null  object
 12  Unnamed: 12  100001 non-null  object
 13  Unnamed: 13  100001 non-null  object
 14  Unnamed: 14  100001 non-null  object
 15  Unnamed: 15  100001 non-null  object
 16  Unnamed: 16  100001 non-null  object
 17  Unnamed: 17  100001 non-null  object
 18  Unnamed: 18  100001 non-null  object
 19  Unnamed: 19  100001 non-null  object
 20  Unnamed: 20  100001 non-null  object
 21  Unnamed: 21  100001 non-null  object
 22  Unnamed: 22  100001 non-null  object
 23  Unnamed: 23  100001 non-null  object
 24  y            100003 non-null  object
dtypes: object(25)
memory usage: 19.1+ MB

None

In [20]:
#TRATAR AS COLUNAS
# profissão
    # engenheiro - 1
    # advogado - 2
    # cientista - 3
    # ator - 4
    # mecanico - 5
# mix credito
# comportamento_pagamento

from sklearn.preprocessing import LabelEncoder
tabela = pd.read_csv("clientes.csv")

codificador = LabelEncoder()

tabela["profissao"] = codificador.fit_transform(tabela["profissao"])

tabela["mix_credito"] = codificador.fit_transform(tabela["mix_credito"])

tabela ["comportamento_pagamento"] = codificador.fit_transform(tabela["comportamento_pagamento"])
display(tabela.info())

C:\Users\TecnoSys\AppData\Local\Temp\ipykernel_5948\610362204.py:12: DtypeWarning: Columns (0,1,2,4,5,6,7,8,9,10,11,13,14,15,16,18,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  tabela = pd.read_csv("clientes.csv")

KeyError: 'profissao'

In [17]:
# Y = Quem você quer prever o Score de crédito
y = tabela["score_credito"]

# X = Colunas que você vai usar para prever o score de crédito
x= tabela.drop(columns=["id_cliente", "score_credito"])

from sklearn.model_selection import train_test_split

x_treino, x_teste, y_treino, y_teste = train_test_split(x, y)

KeyError: 'score_credito'

In [14]:
# Passo 3: Criar o modelo de IA-> Prever o Score de crédito

# Árvore de decisão-> RandomForrest
# KNN-> Vizinhos próxios
# Importar a IA
tabela = pd.read_csv("clientes.csv")
import sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Criar a IA
modelo_arvoredecisão = RandomForestClassifier()
modelo_knn = KNeighborsClassifier()

# Treinar a IA
modelo_arvoredecisão.fit(x_treino, y_treino)
modelo_knn.fit(x_treino, y_treino)

C:\Users\TecnoSys\AppData\Local\Temp\ipykernel_5948\3341015633.py:6: DtypeWarning: Columns (0,1,2,4,5,6,7,8,9,10,11,13,14,15,16,18,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  tabela = pd.read_csv("clientes.csv")

NameError: name 'x_treino' is not defined